  # parser = argparse.ArgumentParser(description="PyTorch CIFAR10 Training")
  #   parser.add_argument("--lr", default=0.1, type=float, help="learning rate")
  #   parser.add_argument(
  #       "--resume", "-r", action="store_true", help="resume from checkpoint"
  #   )
  #   parser.add_argument("--seed", default=0, type=int, help="random seed")
  #   parser.add_argument("--batch-size", default=128, type=int, help="batch size")
  #   parser.add_argument("--epochs", default=10, type=int, help="epochs")
  #   args = parser.parse_args()

lr: 0.1
resume: false
seed: 0
batch_size: 10000
epochs: 20

